### ISSUE TITLE
bug: '<< ' 또는 '< ' 만 입력하면 syntax error가 아니라 seg fault가 발생함

### ISSUE THREAD

**Issue by eesum** [eesum/minishell_42#20]
<<만 입력하면 괜찮은데 뒤에 space가 들어가면 seg fault가 발생하고 있어요!

**Comment by seohyeki** [comment]
redirection node가 current이고,
current->next == NULL일때 (((current->next)->content)->type) != 0을 확인하다가 seg fault발생
current->next == NULL 이면 확인하지 않고 syntax error 발생하도록 수정
